services:
  worker:
    build:
      context: ../
      target: oms-worker
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
      - BILLING_API_URL=http://api:8081
      - ORDER_API_URL=http://api:8082
      - SHIPMENT_API_URL=http://api:8083
      - FRAUD_API_URL=http://api:8084
    command: ["-k", "supersecretkey"]
    restart: on-failure
  api:
    build:
      context: ../
      target: oms-api
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
      - BIND_ON_IP=0.0.0.0
      - BILLING_API_PORT=8081
      - ORDER_API_PORT=8082
      - SHIPMENT_API_PORT=8083
      - FRAUD_API_PORT=8084
    command: ["-k", "supersecretkey"]
    volumes:
      - api-data:/data
    restart: on-failure
  codec-server:
    build:
      context: ../
      target: oms-codec-server
    # Adjust the web server URL to point to your Temporal Web instance.
    command: ["-p", "8089", "-u", "http://localhost:8080"]
    # If you are using a Temporal CLI's start-dev you can use this:
    # command: ["codec-server", "-p", "8089", "-u", "http://localhost:8233"]
    ports:
      - "8089:8089"
    restart: on-failure
  web:
    image: ghcr.io/temporalio/reference-app-orders-web:latest
    depends_on:
      - api
    environment:
      - ORIGIN=http://localhost:3000
      - BILLING_API_URL=http://api:8081
      - ORDER_API_URL=http://api:8082
      - SHIPMENT_API_URL=http://api:8083
      - FRAUD_API_URL=http://api:8084
    ports:
      - "3000:3000"
    restart: on-failure
volumes:
  api-data: