services:
  worker:
    build:
      context: ../
      target: oms-worker
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
      - BILLING_API_URL=http://api:8081
      - ORDER_API_URL=http://api:8082
      - SHIPMENT_API_URL=http://api:8083
      - FRAUD_API_URL=http://api:8084
    command: ["worker", "-k", "supersecretkey"]
    restart: on-failure
  api:
    build:
      context: ../
      target: oms-api
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
      - BIND_ON_IP=0.0.0.0
      - BILLING_API_PORT=8081
      - ORDER_API_PORT=8082
      - SHIPMENT_API_PORT=8083
      - FRAUD_API_PORT=8084
    command: ["api", "-k", "supersecretkey"]
    restart: on-failure
  codec-server:
    build:
      context: ../
      target: oms-codec-server
    command: ["codec-server", "-p", "8089", "-u", "http://localhost:8233"]
    ports:
      - "8089:8089"
    restart: on-failure
  web:
    build:
      context: ../
      target: web
    depends_on:
      - api
    environment:
      - ORIGIN=http://localhost:3000
      - BILLING_API_URL=http://api:8081
      - ORDER_API_URL=http://api:8082
      - SHIPMENT_API_URL=http://api:8083
      - FRAUD_API_URL=http://api:8084
    ports:
      - "3000:3000"
    restart: on-failure