apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: main-api
    app.kubernetes.io/name: oms
  name: main-api
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: main-api
      app.kubernetes.io/name: oms
  serviceName: main-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: main-api
        app.kubernetes.io/name: oms
    spec:
      containers:
        - args:
            - -k
            - supersecretkey
            - -s
            - order,shipment
          env:
            - name: BIND_ON_IP
              value: 0.0.0.0
            - name: ORDER_API_PORT
              value: "8082"
            - name: SHIPMENT_API_PORT
              value: "8083"
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend.temporal:7233
          image: reference-app-orders-go-api:latest
          name: main-api
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: main-api-data
          imagePullPolicy: Never
      volumes:
        - name: main-api-data
          persistentVolumeClaim:
            claimName: main-api-data
      enableServiceLinks: false
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/component: main-api-data
          app.kubernetes.io/name: oms
        name: main-api-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
