apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: mongo
    app.kubernetes.io/name: oms
  name: mongo
  namespace: oms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
