name: Continuous Integration
on:
  pull_request:
  
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Lint
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml

      - name: Test
        run: go test ./...

