name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push oms-go-worker Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: linux/amd64,linux/arm64
          target: oms-worker
          tags: ghcr.io/temporalio/reference-app-orders-go-worker:latest
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build and push oms-go-api Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: linux/amd64,linux/arm64
          target: oms-api
          tags: ghcr.io/temporalio/reference-app-orders-go-api:latest
          push: ${{ github.event_name != 'pull_request' }}
